# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b6e165fe3436f8a2add8b00917ad8097c4b0898cd20a7637beee3e6a9e4d83cdc708ee30ac82daf35e89da2799c0e16d7ab090b4319dea341b626fbc2d6a069
  mapbox_api_key: <%= ENV["MAPBOX_API_KEY"] %>

test:
  secret_key_base: cb443604e661c34575f5325dac64dc160cb9ca176205801354337bd2682331a61e885d40fed353b753e1ecb65c31b6d0c8135fbec9d554d97d806bd1b59485ef
  mapbox_api_key: <%= ENV["MAPBOX_API_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mapbox_api_key: <%= ENV["MAPBOX_API_KEY"] %>